- name: play variables
  hosts: localhost
  vars:
    URL: play.example.com
  tasks:
    - name: print play variable
      ansible.builtin.debug:
        msg: URL = {{ URL }}

- name: play variables from Files
  hosts: localhost
  ## vars_files works only on play level
  vars_files:
    - var.yml
  tasks:
    - name: print play variable from File
      ansible.builtin.debug:
        msg: URL = {{ URL }}

- name: Task Level Variables
  hosts: localhost
  tasks:
    - name: print play variable from File
      vars: ## this vars are only for this task, next task on same play cannot access it
        URL: task.example.com
      ansible.builtin.debug:
        msg: URL = {{ URL }}

