- name: play variables
  hosts: localhost
  vars:
    URL: play.example.com
  tasks:
    - name: print play variable
      ansible.builtin.debug:
        msg: URL = {{ URL }}


- name: play variables from file
  hosts: localhost
  vars_file:
    - var.yml
  tasks:
    - name: print play variable
      ansible.builtin.debug:
        msg: URL = {{ URL }}

